version: "3"

services:
  pylint:
    build:
      context: ./pylint/
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ../app
        target: /app/
    tty: true
    stdin_open: true
  unittest:
    build:
      context: ./unittest/
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ../app
        target: /app/
    tty: true
    stdin_open: true
  radon-cc:
    build:
      context: ./radon-cc/
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ../app
        target: /app/
    tty: true
    stdin_open: true
  radon-raw:
    build:
      context: ./radon-raw/
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ../app
        target: /app/
    tty: true
    stdin_open: true
  app:
    build:
      context: /home/runner/TP4-CD-githubaction/
      dockerfile: docker-app/python/Dockerfile
    ports:
      - 5000:5000
  robot:
    build:
      context: ./robot/
      dockerfile: ./Dockerfile
    environment:
      URL: app
      PORT: 5000
    depends_on:
      - app
    volumes:
      - type: bind
        source: ../app
        target: /app/
    tty: true
    stdin_open: true
