steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "europe-west1-docker.pkg.dev/tp4-cd-400812/docker-repo/tp4-cd:latest", "../docker-app/python/Dockerfile"]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "europe-west1-docker.pkg.dev/tp4-cd-400812/docker-repo/tp4-cd:latest"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=./prod_env/deployment.yml
  - --image=europe-west1-docker.pkg.dev/tp4-cd-400812/docker-repo/tp4-cd:latest
  - --location=europe-west1-b
  - --cluster=deploying-builds