apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app

spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - image: khagu/image-tp3:latest
          name: demo-app
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
  selector:
    matchLabels:
      app: demo-app

---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  selector:
    app: demo-app
  ports:
  - port: 80
    targetPort: 5000

