apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-app
  name: demo-app

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - image: europe-west1-docker.pkg.dev/tp4-cd-400812/docker-repo/tp4-cd
          name: demo-app
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: env-config-demo
  selector:
    matchLabels:
      app: demo-app