apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: myapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: europe-west1-docker.pkg.dev/tp4-cd-403915/docker-repo/tp4-cd:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  selector:
    app: demo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000

