plugin: gcp_compute
zones: # populate inventory with instances in these regions
  - eu-west1-b # Change me
projects:
  - tp4-cd # Change me
service_account_file: ./ansible_service_account.json # Change me
auth_kind: serviceaccount
keyed_groups:
  # Create groups from GCE labels
  - key: labels
    prefix: label
  - key: zone
    prefix: zone
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
