# playbook.yml

- name: Install and configure python app
  hosts: python-app-instance
  gather_facts: false
  become: true

  tasks:
    # Tâches pour wordpress
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install required packages for Docker
      apt:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - docker

    - name: log into docker hub registry
      docker_login:
        email: "{{ hub_docker_email }}"
        username: "{{ hub_docker_user }}"
        password: "{{ hub_docker_password }}"

    - name: ensure a container is running
      docker_container:
        name: "{{ container_name }}"
        state: started
        image: "{{ hub_docker_user }}/{{ image_name }}:{{ image_version }}"
        pull: true
