name: Integration Continue

on:
  push:
    branches:
      - cd

env:
  # Use docker.io for Docker Hub if empty
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}

jobs:
  # creation-service-account:
  #   permissions:
  #     contents: "read"
  #     id-token: "write"
  #   runs-on: ${{ vars.IMAGE_OS }}

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: "Google auth"
  #       id: "auth"
  #       uses: "google-github-actions/auth@v1"
  #       with:
  #         workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"
  #         service_account: "${{ secrets.WORKLOAD_SERVICE_ACCOUNT }}"

  #     - name: "creation du compte de service"
  #       run: |
  #         gcloud config set project ${{ vars.PROJECT_ID }}
  #         gcloud iam service-accounts create sa-terraform \
  #         --description="commpte de service pour terraform" \
  #         --display-name="sa-terraform" \
  #         --member="serviceAccount:sa-terraform@${{ vars.PROJECT_ID }}.iam.gserviceaccount.com" \
  #         --role="roles/editor"

  ###### Check docker image ######
  ################################
  # check-docker-image:
  #   runs-on: ${{ vars.IMAGE_OS }}
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_USER }}
  #         password: ${{ secrets.DOCKER_TOKEN }}

  #     - name: Extract Docker metadata
  #       id: meta
  #       uses: docker/metadata-action@v4.4.0
  #       with:
  #         images: ${{ secrets.DOCKER_USER }}/${{ vars.DOCKER_REPO }}
  #         labels: |
  #           org.opencontainers.image.revision=${{ env.SHA }}
  #         tags: |
  #           type=edge,branch=$repo.default_branch
  #           type=semver,pattern=v{{version}}
  #           type=sha,prefix=,suffix=,format=short

  #     - name: Check image
  #       uses: docker/scout-action@v0.18.1
  #       with:
  #         command: cves
  #         image: ${{ secrets.DOCKER_USER }}/${{ vars.DOCKER_REPO }}:${{ vars.DOCKER_IMAGE_VERSION }}
  #         exit-code: true
  #         # token: ${{ secrets.DOCKER_TOKEN }}

  # deploiement-terraform:
  #   # needs: [check-docker-image]
  #   permissions:
  #     contents: "read"
  #     id-token: "write"
  #   runs-on: ${{ vars.IMAGE_OS }}

  #   steps:
  #     - uses: actions/checkout@v3

  #     # - name: "Google auth"
  #     #   id: "auth"
  #     #   uses: "google-github-actions/auth@v1"
  #     #   with:
  #     #     token_format: "credential"
  #     #     workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"
  #     #     service_account: "${{ secrets.WORKLOAD_SERVICE_ACCOUNT }}"
  #     #     access_token_lifetime: "300s"
  #     - name: Setup terraform
  #       uses: hashicorp/setup-terraform@v2

  #     - name: Terraform Init
  #       run: |
  #         cd terraform
  #         terraform init
  #       env:
  #         GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  #     # - name: Terraform format
  #     #   run: |
  #     #     cd terraform
  #     #     terraform fmt -check
  #     # Generates an execution plan for Terraform
  #     - name: Terraform Plan
  #       run: |
  #         cd terraform
  #         terraform plan -input=false
  #       env:
  #         GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

  #     - name: Terraform Apply
  #       if: github.ref == 'refs/heads/cd' && github.event_name == 'push'
  #       run: |
  #         cd terraform
  #         terraform apply -auto-approve -input=false
  #       env:
  #         GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

  push-docker-image-to-GCR:
    # needs: [check-docker-image]
    runs-on: ${{ vars.IMAGE_OS }}
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3

      - name: "Google auth"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.WORKLOAD_SERVICE_ACCOUNT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: "Build and push"
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: europe-west1-docker.pkg.dev
          project_id: ${{ vars.GCP_PROJECT }}
          image_name: tp4-cd/docker-repo
          image_tag: 1
          dockerfile: ./docker-app/python/Dockerfile
          context: ./

  # Image-deployment:
  #   needs: [deploiement-terraform]
  #   runs-on: ${{ vars.IMAGE_OS }}

  #   steps:
  #     - name: "Google auth"
  #       id: "auth"
  #       uses: "google-github-actions/auth@v1"
  #       with:
  #         workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"
  #         service_account: "${{ secrets.WORKLOAD_SERVICE_ACCOUNT }}"

  #     - name: "compute-ssh"
  #       uses: "google-github-actions/ssh-compute@v0"
  #       with:
  #         instance_name: "python-dev-instance"
  #         zone: "eu-west1-b"
  #         ssh_private_key: "${{ secrets.GOOGLE_CREDENTIALS }}"

  # ansible-playbook:
  #   runs-on: ${{ vars.IMAGE_OS}}
  #   steps:
  #     - name: Install ansible
  #       run: |
  #         if ! command -v ansible &> /dev/null; then
  #         sudo apt update
  #         sudo apt install -y ansible
  #         fi
  #     - name: Run ansible playbook
  #       run: |
