name: Integration Continue

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pylint-test:
    runs-on: ${{ vars.IMAGE_OS }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pylint-json2html
      - name: Analysing the code with pylint
        run: |
          cd app
          mkdir reports
          cd reports
          mkdir pylint
          cd pylint
          pwd

          pylint $(git ls-files '**/*.py') > report.json || exit 0
          pylint-json2html -o report.html report.json
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: pylint result
          path: ./app/reports/pylint

  unittest-test:
    runs-on: ${{ vars.IMAGE_OS }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install html-testRunner
      - name: Analysing the code with unittest
        run: |
          cd app
          python -m unittest ${{ vars.UNITTEST_FILE}}
      - name: Archive report
        uses: actions/upload-artifact@v3
        with:
          name: unittest results
          path: |
            app/reports/unittest/

  robot-test:
    runs-on: ${{ vars.IMAGE_OS }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: install flask dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask

      - name: start flask app
        run: |
          cd app
          flask --app=./main.py run --host=0.0.0.0 &
          sleep 5
      - name: Install robot dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-browser
      - name: Analysing the code with robotframework
        run: |
          cd ${{ vars.ROBOT_FILE_WAY }}
          robot ${{ vars.ROBOT_FILE_NAME }}
      - name: Archive log report and output
        uses: actions/upload-artifact@v3
        with:
          name: robot framework results
          path: |
            app/test/system/
            !app/test/system/machine.robot

  radon-raw-test:
    runs-on: ${{ vars.IMAGE_OS }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install radon
          pip install json2tree
      - name: Analysing the code with radon
        run: |
          pwd
          cd ./app
          mkdir reports
          cd ./reports
          mkdir raw
          cd ../..
          radon raw -j ./app > ./app/reports/raw/report.json; json2tree -j ./app/reports/raw/report.json -o ./app/reports/raw/report.html -t 1
      - name: Archive report
        uses: actions/upload-artifact@v3
        with:
          name: radon raw results
          path: |
            app/reports/raw/

  radon-cc-test:
    runs-on: ${{ vars.IMAGE_OS }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install radon
          pip install json2tree
      - name: Analysing the code with radon
        run: |
          pwd
          cd ./app
          mkdir reports
          cd ./reports
          mkdir cc
          cd ../..
          radon cc -j ./app > ./app/reports/cc/report.json; json2tree -j ./app/reports/cc/report.json -o ./app/reports/cc/report.html -t 1
      - name: Archive report
        uses: actions/upload-artifact@v3
        with:
          name: radon cc results
          path: |
            app/reports/cc/

  build-push-image:
    needs:
      [pylint-test, unittest-test, robot-test, radon-raw-test, radon-cc-test]
    runs-on: ${{ vars.IMAGE_OS }}

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./docker-app/python
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ vars.DOCKER_REPO }}:${{ vars.DOCKER_IMAGE_VERSION }}
