name: Pipeline Dev-env

on:
  push:
    branches:
      - dev

env:
  # Use docker.io for Docker Hub if empty
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}

jobs:
  ###### Deploiement terraform ######
  ###################################
  deploiement-terraform:
    # needs: [push-docker-image-to-GAR]
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ${{ vars.IMAGE_OS }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          export DOCKER_IMAGE_VERSION="${{ env.DOCKER_IMAGE_VERSION}}"
          cd dev_env
          terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          DOCKER_IMAGE_VERSION: ${{ vars.DOCKER_IMAGE_VERSION}}

      - name: Terraform Plan
        run: |
          export DOCKER_IMAGE_VERSION="${{ env.DOCKER_IMAGE_VERSION}}"
          cd dev_env
          terraform plan -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          DOCKER_IMAGE_VERSION: ${{ vars.DOCKER_IMAGE_VERSION}}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
        run: |
          export DOCKER_IMAGE_VERSION="${{ env.DOCKER_IMAGE_VERSION}}"
          cd dev_env
          terraform apply -auto-approve -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          DOCKER_IMAGE_VERSION: ${{ vars.DOCKER_IMAGE_VERSION}}
